// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk_2jzrjvJ8ugOVPVVFiVEofZ-24buMf4',
    appId: '1:152431943196:web:936763e35c657a4eb109d9',
    messagingSenderId: '152431943196',
    projectId: 'chaser-runner',
    authDomain: 'chaser-runner.firebaseapp.com',
    storageBucket: 'chaser-runner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjQ5lXhdMpBBtWLZtivfXvlcXyTB2_gLo',
    appId: '1:152431943196:android:d25d08026b71707fb109d9',
    messagingSenderId: '152431943196',
    projectId: 'chaser-runner',
    storageBucket: 'chaser-runner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbIq6WSXelTD4ASsImtDsWN_zKDHMkPh4',
    appId: '1:152431943196:ios:9ba6d20215f6ca0cb109d9',
    messagingSenderId: '152431943196',
    projectId: 'chaser-runner',
    storageBucket: 'chaser-runner.firebasestorage.app',
    iosBundleId: 'com.chaser.chaser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbIq6WSXelTD4ASsImtDsWN_zKDHMkPh4',
    appId: '1:152431943196:ios:9ba6d20215f6ca0cb109d9',
    messagingSenderId: '152431943196',
    projectId: 'chaser-runner',
    storageBucket: 'chaser-runner.firebasestorage.app',
    iosBundleId: 'com.chaser.chaser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk_2jzrjvJ8ugOVPVVFiVEofZ-24buMf4',
    appId: '1:152431943196:web:36196b503a3108b5b109d9',
    messagingSenderId: '152431943196',
    projectId: 'chaser-runner',
    authDomain: 'chaser-runner.firebaseapp.com',
    storageBucket: 'chaser-runner.firebasestorage.app',
  );
}
