import 'package:chaser/models/session.dart';
import 'package:chaser/services/firebase/auth_service.dart';
import 'package:chaser/services/firebase/firestore_service.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

class CreateSessionScreen extends ConsumerStatefulWidget {
  const CreateSessionScreen({super.key});

  @override
  ConsumerState<CreateSessionScreen> createState() => _CreateSessionScreenState();
}

class _CreateSessionScreenState extends ConsumerState<CreateSessionScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _firestoreService = FirestoreService(); // TODO: Use provider
  
  String _gameMode = 'original';
  int _durationDays = 7;
  bool _isLoading = false;

  Future<void> _createSession() async {
    if (!_formKey.currentState!.validate()) return;
    
    // Get current user ID
    // Note: In real app, use ref.read(currentUserProvider)
    // final user = context.mounted ? null : null; // placeholder (removed unused)
    // We'll trust auth state is present if we are here
    
    // Hack: getting user directly from AuthService instance for now
    // Ideally use a provider
    final authService = AuthService();
    final userUid = authService.currentUser?.uid;
    
    if (userUid == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Error: Not authenticated')),
      );
      return;
    }

    setState(() => _isLoading = true);

    try {
      final session = SessionModel(
        id: '', // Generated by firestore
        name: _nameController.text.trim(),
        ownerId: userUid,
        createdBy: userUid,
        gameMode: _gameMode,
        durationDays: _durationDays,
      );

      final sessionId = await _firestoreService.createSession(session);
      
      if (mounted) {
        context.replace('/session/$sessionId');
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to create session: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Create New Game')),
      body: Form(
        key: _formKey,
        child: ListView(
          padding: const EdgeInsets.all(16),
          children: [
            TextFormField(
              controller: _nameController,
              decoration: const InputDecoration(
                labelText: 'Session Name',
                hintText: 'e.g. Office Challenge',
              ),
              validator: (value) => 
                  value == null || value.isEmpty ? 'Required' : null,
            ),
            const SizedBox(height: 16),
            
            DropdownButtonFormField<String>(
              initialValue: _gameMode,
              decoration: const InputDecoration(labelText: 'Game Mode'),
              items: const [
                DropdownMenuItem(value: 'original', child: Text('Original Tag')),
                DropdownMenuItem(value: 'target', child: Text('Target Mode')),
              ],
              onChanged: (val) => setState(() => _gameMode = val!),
            ),
            const SizedBox(height: 16),
            
            DropdownButtonFormField<int>(
              initialValue: _durationDays,
              decoration: const InputDecoration(labelText: 'Duration'),
              items: const [
                DropdownMenuItem(value: 3, child: Text('3 Days')),
                DropdownMenuItem(value: 7, child: Text('7 Days')),
                DropdownMenuItem(value: 14, child: Text('14 Days')),
                DropdownMenuItem(value: 30, child: Text('30 Days')),
              ],
              onChanged: (val) => setState(() => _durationDays = val!),
            ),
            const SizedBox(height: 32),
            
            ElevatedButton(
              onPressed: _isLoading ? null : _createSession,
              child: _isLoading 
                  ? const CircularProgressIndicator() 
                  : const Text('Create Game'),
            ),
          ],
        ),
      ),
    );
  }
}
